04_タスクに関するシステムスペックを修正
atsushi101011/rspec_app_exam pull request #1
Opened 2021-01-18 23:30 UTC by atsushi101011

RSpec力 › 04_テストコード修正のPRです。チェックよろしくお願いします！

2021-01-19 07:02 UTC, yuji91 requested changes
こちら2点指摘しました！

それ以外の修正内容については、問題ありません。

2021-01-19 07:02 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content('Task was successfully destroyed.')
削除が正しくできているかの確認を「flashメッセージの判定」で行うと以下の問題があります。

1. 複数件からのタスクデータ削除のテストケースにおいて、削除対象以外を誤って削除されてもテストが通ってしまう。
2. flashメッセージとテストケースに依存性が出来てしまい、メッセージが変わるとテストが失敗する。

他機能との依存性があるとテストケースが実装側の変更に弱く、メンテナンスコストが高いテストになります。

失敗例のPullRequestでの指摘事項をヒントに対応をお願いします。
[![Image from Gyazo](https://i.gyazo.com/9f6478652883c2bd42f6cdb751f33bfd.png)](https://gyazo.com/9f6478652883c2bd42f6cdb751f33bfd)

2021-01-19 22:58 UTC, atsushi101011 commented on spec/system/task_spec.rb
> +      let(:task) {create(:task) }
6e8fe57 こちら修正しました。

2021-01-19 22:59 UTC, atsushi101011 commented on spec/system/task_spec.rb
> +        expect(page).to have_content('Task was successfully destroyed.')
6c5c1b8 失敗例での指摘事項をヒントに、修正しました。

2021-01-20 01:44 UTC, yuji91 approved these changes
LGTMです！

2021-01-20 08:59 UTC, merged